### ISSUE TITLE
Flux Tools Update.

### ISSUE THREAD

**Issue by ShadoW-Shinigami** [yhayano-ponotech/ComfyUI-Fal-API-Flux#11]
Is there a possibility of getting the latest Flux-Tools Endpoints that have been added to fal? Especially the Fill and Redux Endpoints? They will be super useful for creating inpaint workflows and AIO workflows.

https://fal.ai/flux-tools

Thank you for this repo regardless

**Comment by yhayano-ponotech** [comment]
@ShadoW-Shinigami 
Hi, Thank you for using this custom node. I will add functions for Flux-Tools. Wait a while to complete it.

**Comment by yhayano-ponotech** [comment]
@ShadoW-Shinigami 
I added new nodes for Flux-Tools.
