### ISSUE TITLE
Could the node support Flux .1 Pro?

### ISSUE THREAD

**Issue by ultimatech-cn** [yhayano-ponotech/ComfyUI-Fal-API-Flux#3]
The model is available on https://fal.ai/models/fal-ai/flux-pro

**Comment by yhayano-ponotech** [comment]
No, this node is not compatible with flux-pro. I will add it soon.

**Comment by ultimatech-cn** [comment]
Great.  Looking forward to seeing it soon

**Comment by yhayano-ponotech** [comment]
@ultimatech-cn 
I Added support for FLUX.1[pro].

**Comment by ultimatech-cn** [comment]
Thank you!
