### ISSUE TITLE
Would you consider I2I with Lora model as well?

### ISSUE THREAD

**Issue by KINGLIFER** [yhayano-ponotech/ComfyUI-Fal-API-Flux#4]
https://fal.ai/models/fal-ai/flux-lora/image-to-image

This also has a strength option that would need to be added as well

**Comment by yhayano-ponotech** [comment]
@KINGLIFER 
I missed the function. I will support it.

**Comment by yhayano-ponotech** [comment]
@KINGLIFER 
I added support for image-to-image.
