### ISSUE TITLE
Flux Pro 1.1 and custom resolutions?

### ISSUE THREAD

**Issue by festivus37** [yhayano-ponotech/ComfyUI-Fal-API-Flux#6]
Hi there, thanks so much for these comfyui nodes. Can I ask for the new flux pro 1.1 to be available as a node, and separately, the ability to specify the desired resolution? I'm including a screenshot, where on fal.ai I can specify a resolution, so it would be great to be able to do that with these nodes as well so we're not limited to 1024 res. Thanks for your help.

![image](https://github.com/user-attachments/assets/821fef21-652c-4517-a098-a5e9704ea88e)

**Comment by yhayano-ponotech** [comment]
@festivus37 
Hi there, thank you for your suggestion! We will add support for Flux Pro 1.1, and we'll also make it possible to specify a custom resolution as requested. Thanks again for your input!

**Comment by yhayano-ponotech** [comment]
@festivus37 
I have finished adding the Flux1.1[pro] node, as well as the "width" and "height" parameters. However, the "image_size" input is redundant because "width" and "height" serve as an alternative to "image_size."
