### ISSUE TITLE
Staacking LoRA's?

### ISSUE THREAD

**Issue by lideborg** [yhayano-ponotech/ComfyUI-Fal-API-Flux#8]
Hey, 
Thank you for the great nodes. Just a question is it possible to stack multiple LoRA's similar to how they do on the website?

**Comment by yhayano-ponotech** [comment]
Hi @lideborg ,
The function you mentioned is currently disabled because fal.ai couldn't previously stack LoRAs. However, it seems that they might have implemented this feature now, so I will enable it after confirming.

**Comment by lideborg** [comment]
Cool, thank you!

**Comment by yhayano-ponotech** [comment]
@lideborg 
I have promptly adjusted this node to be able to stack up to five LoRAs.
